name = "grand-test"
main = "src/index.js"
compatibility_date = "2023-11-01"

[vars]
# No additional variables needed

[[kv_namespaces]]
binding = "NEET_PG_TRACKER"
id = "10da7d5c175743c68fd752d7e21f3b19"  # Replace with your actual KV namespace ID

